version: "3"
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./compose/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./compose/redis:/data
